### ISSUE TITLE
Update to 1.20.1?

### ISSUE THREAD

**Issue by lxly9** [ImLavenderYT/Tombstones#1]
Hiii, i love this mod so much (the model is sooo pretty) and was hoping that it may be updated to 1.20.1!

**Comment by ImLavenderYT** [comment]
Done. Glad you like it! I'm going to add more things to it for Halloween this year, so stay tuned for that!

**Comment by lxly9** [comment]
Yay! Thank you very much!! Im excited to see what you will add o.0
